// <auto-generated />
namespace Astec.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Add_log : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_log));
        
        string IMigrationMetadata.Id
        {
            get { return "202001140913392_Add_log"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
